spring:
  application:
    name: users-service
  config:
    import: "optional:configserver:http://config-user:config-password@localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888
      username: config-user
      password: config-password
      fail-fast: false
      retry:
        initial-interval: 2000
        max-attempts: 5
 
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  grpc:
    server:
      port: 9090
      reflection:
        enabled: true

# Server Configuration
server:
  port: 8082

# Logging
logging:
  level:
    # Application packages
    "[com.reactiverates.users]": TRACE
    "[com.reactiverates]": DEBUG

    # Spring Boot components
    "[org.springframework]": DEBUG
    "[org.springframework.web]": DEBUG
    "[org.springframework.web.servlet]": DEBUG
    "[org.springframework.web.filter]": DEBUG
    "[org.springframework.security]": DEBUG
    "[org.springframework.security.web]": DEBUG
    "[org.springframework.security.oauth2]": DEBUG

    # Database and JPA/Hibernate
    "[org.hibernate]": DEBUG
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
    "[org.springframework.orm.jpa]": DEBUG
    "[org.springframework.jdbc]": DEBUG

    # gRPC
    "[io.grpc]": DEBUG
    "[io.grpc.netty]": DEBUG
    "[net.devh.boot.grpc]": DEBUG

    # Eureka client
    "[com.netflix.discovery]": DEBUG
    "[com.netflix.eureka]": DEBUG

    # HTTP clients
    "[org.springframework.web.client]": DEBUG
    "[org.apache.http]": DEBUG

    # Configuration
    "[org.springframework.cloud.config]": DEBUG
    "[org.springframework.cloud.context]": DEBUG

    # Swagger/OpenAPI
    "[org.springdoc]": DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    level: "com.reactiverates.users: TRACE"

# Swagger UI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
    enabled: true
    config-url: /api-docs/swagger-config
    url: /api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

jwt:
  secret: mySecretKeymySecretKeymySecretKeymySecretKey

openapi:
  server:
    dev:
      url: http://localhost:${server.port}
      description: Локальная среда разработки
    prod:
      url: https://api.reactiverates.com
      description: Продакшн сервер