spring:
  application:
    name: Users
  
  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  grpc:
    server:
      port: 9090
      reflection:
        enabled: true

# Server Configuration
server:
  port: 8080

# Logging
logging:
  level:
    com.reactiverates.users: DEBUG
    org.springframework.security: DEBUG
    org.springdoc: DEBUG

# Swagger UI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
    enabled: true
    config-url: /api-docs/swagger-config
    url: /api-docs

# JWT Configuration
jwt:
  secret: mySecretKeymySecretKeymySecretKeymySecretKey
